### ISSUE TITLE
正規化後のデータを確認するところ：range(27) -> range(28)

### ISSUE THREAD

**Issue by minatu2d** [kurupical/keras_handson#1]
Handsonを作ってもらって
ありがとうございます。
ちょっと以下の点を気になるので
Issueを作ります。

```
for i in range(3):
    print("********************************")
    print("x_train[{}]のデータ".format(i))
    print("********************************\n")
    
    for j in range(27):
        w_str = ""
        for k in range(27):
            w_str2 = "{0:03d} ".format(int(x_train[i][28 * j + k]))
            w_str = w_str + w_str2 
        print(w_str)
    print("\n")
```

１．上記のrange(27)はrange(28）の誤りではないでしょうか？

２．上記ではx_train[i]がintへCastされているが。
1.0未満の値が0になっているので
ちょっとわかりにくいと思います。

``
w_str2 = "{0:0.0f} ".format(x_train[i][28 * j + k])
``
とか
``
w_str2 = "{0:0.1f} ".format(x_train[i][28 * j + k])
``
とか書いたらちょっとわかりやすくなりそうです。
以下のようなイメージです。

![nnnnn](https://user-images.githubusercontent.com/9568154/36585104-cfbb56f2-18bf-11e8-9bfa-d4c966e01f9a.PNG)

**Comment by kurupical** [comment]
ありがとうございます。
>１．上記のrange(27)はrange(28）の誤りではないでしょうか？
おっしゃるとおりです。修正しました。

>２．上記ではx_train[i]がintへCastされているが。
各配列の値を見るのが目的だったのですが、255を掛けるのを忘れていました。
修正しました。
